### ISSUE TITLE
Нефункціональні вимоги

### ISSUE THREAD

**Issue by don585** [prihodkoserzh/reqs#1]
https://github.com/prihodkoserzh/reqs/blob/ef195e3d4d8a7fcd261a1b7995f93a6fa2a8cfc6/%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D1%96%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%96%20%D0%B2%D0%B8%D0%BC%D0%BE%D0%B3%D0%B8%20(1).txt#L17
Необхідно додати вимоги, щодо підтримки мобільної версії

**Comment by prihodkoserge** [comment]
Буде достатньо розглянути операційны системи Android та IOS?

**Comment by don585** [comment]
Так, оскільки вони є найбільш розповсюдженими
