### ISSUE TITLE
1.1

### ISSUE THREAD

**Issue by IanaKhitsko** [prihodkoserzh/reqs#5]
1.1. Система повинна виконувати розподіл ролей на відвідувача

Відвідувача - з великої літери?

**Comment by prihodkoserge** [comment]
Згоден

**Comment by prihodkoserge** [comment]
@IanaKhitsko виправлено в https://github.com/prihodkoserzh/reqs/commit/5599ee6d58e94b9e93d22fd72836fb518d4301c1
